#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

LABEL_FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
# FONT="FiraCode Nerd Font:Regular:15.0" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
FONT="Hack Nerd Font:Bold:17.0" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=2 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=1
POPUP_CORNER_RADIUS=11

SHADOW=on

# Setting up the general bar appearance and default values
# # y_offset=8                                       
sketchybar --bar     height=25                                         \
                     color=$BAR_COLOR                                  \
                     shadow=$SHADOW                                    \
                     position=top                                      \
                     sticky=on                                         \
                     blur_radius=20                                    \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$LABEL_FONT:Semibold:14.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
# Center

# Right

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
